### ISSUE TITLE
Getting error Value of optional type 'Unmanaged<CFArray>?' must be unwrapped to refer to member 'takeRetainedValue' of wrapped base type 'Unmanaged<CFArray>' on OS 11.6

### ISSUE THREAD

**Issue by amrinder2105** [dsmelov/simsim#60]
I'm trying to run application on macOS BigSur 11.6 M1 chip and getting error Value of optional type 'Unmanaged<CFArray>?' must be unwrapped to refer to member 'takeRetainedValue' of wrapped base type 'Unmanaged<CFArray>'.

I tried making changes with possible solutions but it still not working. Please check this and let me know what I have to do to run this on my system.

**Comment by gsl-anthonymerle** [comment]
Is this repo still maintained ? Did you managed to work around the error @amrinder2105 ?

**Comment by DesmanLead** [comment]
@gsl-anthonymerle we're not able to reproduce it. Could you debug it, please?

**Comment by gsl-anthonymerle** [comment]
@DesmanLead Yes, I just fixed errors on myself, but I'll dive into the context so that you can hopefully see the same things

I'm currently on MacOS Montery version 12.2.1 (21D62), with an XCode version 13.4.1 (13F100).
As for the repository, I downloaded the master branch as a .zip file

Then I tried to build and got the few errors (Unmanaged<***> not unwraped)

The fix was mostly to use Xcode's auto fix feature which adviced to add the optional chaining `?` when needed, and for one line to specify something instead of a `nil` value.

For the `nil` value, it was in the SimSim/Settings.swift file, at line 48, replacing:
`                    LSSharedFileListInsertItemURL(loginItems,
                                                  nil, nil, nil,
                                                  appURL as CFURL, nil, nil)?.release()
`
by
`                    LSSharedFileListInsertItemURL(loginItems,
                                                  kLSSharedFileListItemBeforeFirst as! LSSharedFileListItem, nil, nil,
                                                  appURL as CFURL, nil, nil)?.release()
`
(note the ad of `kLSSharedFileListItemBeforeFirst as! LSSharedFileListItem` for the second parameter. It's totaly arbitrary, I had no idea of what I was doing on this part as I didn't put too much time on reading&understanding the doc, but compilation succeed and it launched)

**Comment by DesmanLead** [comment]
I see. It's not that easy to add the app as a login item, the old approach doesn't work anymore. I'll disable this feature for now.

**Comment by gsl-anthonymerle** [comment]
Yes, I can imagine, and Apple may event have made it harder through updates because of their strong focus on user's privacy and activity control :x

But in any case, I'm glad I helped and you came up with a solution 🙏 

Have a great day ! :)
